{
  "openapi": "3.0.0",
  "info": {
    "title": "Swagger",
    "description": "Essa é uma documentação sobre o desafio introdução ao SWAGGER.",
    "version": "1.0.0"
  },
  "paths": {
    "/users": {
      "post": {
        "tags": ["users"],
        "summary": "Criar um novo usuário.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "John Doe",
                  "email": "johndoe@example.com"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                },
                "examples": {
                  "$ref": "#/components/examples/user"
                }
              }
            }
          },
          "400": {
            "description": "User already exists!",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "error": "User already exists!"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["users"],
        "summary": "Retorna todos os usuários.",
        "parameters": [
          {
            "name": "user_id",
            "in": "header",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                },
                "examples": {
                  "users": [
                    {
                      "$ref": "#/components/examples/user/value"
                    },
                    {
                      "$ref": "#/components/examples/user/value"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "User already exists!",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "error": "User does not exists!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": ["users"],
        "summary": "Retorna um usuário específico.",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "examples": {
                  "$ref": "#/components/examples/user"
                }
              }
            }
          },
          "404": {
            "description": "User does not exists!",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "error": "User does not exists!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/admin": {
      "patch": {
        "tags": ["users"],
        "summary": "Torna um usuário admin.",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "examples": {
                  "user": {
                    "value": {
                      "id": "e0565653-3e96-426e-9253-3770d04c2fe3",
                      "name": "John Doe",
                      "email": "johndoe@example.com",
                      "admin": true,
                      "created_at": "2021-03-18T23:38:47.631Z",
                      "updated_at": "2021-03-18T23:38:47.631Z"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User does not exists!",
            "content": {
              "application/json": {
                "examples": {
                  "error": {
                    "value": {
                      "error": "User does not exists!"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "user": {
        "value": {
          "id": "e0565653-3e96-426e-9253-3770d04c2fe3",
          "name": "John Doe",
          "email": "johndoe@example.com",
          "admin": false,
          "created_at": "2021-03-18T23:38:47.631Z",
          "updated_at": "2021-03-18T23:38:47.631Z"
        }
      }
    }
  }
}
